### ISSUE TITLE
[CAPTCHA]

### ISSUE THREAD

**Issue by vigo2** [Kruhlmann/gatekeeper#100]
# CAPTCHA issue

CAPTCHA ID: `2419c0eb-ee1a-4752-85f9-8fd8bf827478\06eb2f3f-f997-40e9-87d6-1dc7cd7e0f79`

Captcha question is:

"You (a non-binary human DPS fury warrior in <Scrawny Feet Guys>) are attacking a level 58 Firewalker from the front using your 2 handed mace

Given these parameters what is the hit from gear required to reach your white hit cap (rounded up to nearest 1/10th)?"

As per "Attack table", the formula applying should be "If the target is a mob and defense minus attack rating is 10 or less: MissChance = 5% + (TargetLevel\*5 - AttackerSkill) \* 0.1%", or 5% + (58\*5 - 305) \* 0.1% = 3.5% in this case. The Captcha-expected answer is 4.0% however.

If "non-binary" is supposed to mean that Mace/Sword/Axe specs don't apply, then I'd propose you add a glossary to the captchas (which should also state that the attacking warrior is a canonical level 60, with maxed out defense and weapon skills)

**Comment by Kruhlmann** [comment]
Gender doesn't change the attack table.

**Comment by vigo2** [comment]
The actual bug report is the discrepancy between 3.5% (as per "Attack table" formula) vs. 4.0% as the Captcha-expected answer.

**Comment by vigo2** [comment]
At least I know where "non-binary" is coming from. It'd be less irritating simply leaving male/female/non-binary out of the the Captcha, since they're not mechanics related in any way, shape, or form.
