### ISSUE TITLE
[CAPTCHA]

### ISSUE THREAD

**Issue by Jon-Wagner** [Kruhlmann/gatekeeper#109]
# CAPTCHA issue

CAPTHCA ID: `5517eb91-569b-4af8-8296-3aa9be59bb91\4a18a020-0082-41f3-ada2-4bf26ae7d637

Question text:
You (a level 60 non-binary troll DPS fury warrior in <Vacuous Children>) are attacking a level 59 Firewalker from behind using your dual wielded daggers. You have max weapon skills and no other source of +weapon skill.

Given these parameters what is the hit from gear required to reach your yellow hit cap (rounded up to nearest 1/10th)?

Reasoning:
For yellow hits the formula is  MissChance = 5% + (TargetLevel*5 - AttackerSkill) * 0.1%
Filling in the values we have 5% + (59*5 - 300) * .1% = 5% + (295-300) *.1% = 5% -.5%. = 4.5%

Problem:
4.5 is not accepted as the correct answer, so either I'm missing something about applying the formulas or the accepted answer is the wrong answer.

**Comment by Kruhlmann** [comment]
You're right, the answer *should* indeed be 4.5. The answer is 5 so you can use that to complete the captcha. I'll keep the issue open until I fix the bug.

**Comment by Kruhlmann** [comment]
After looking at the problem I can conclude that the answer is indeed 5. You are not able to get less than 1% hit from gear, and as such you will need 5 percent hit from gear to be hit capped.
