### ISSUE TITLE
Verify the results of the hit chance generator

### ISSUE THREAD

**Issue by Kruhlmann** [Kruhlmann/gatekeeper#2]
Verify that the results generated from the hit chance generated are consistent with the information available in the [attack table](https://github.com/magey/classic-warrior/wiki/Attack-table)

**Comment by Kruhlmann** [comment]
To do this generate a few sample hit chance captchas and calculate them using the attack table formulas to verify the results.

**Comment by ResultsMayVary** [comment]
This issue should be resolved with the PR merged
