### ISSUE TITLE
Add player parry chance generator

### ISSUE THREAD

**Issue by Kruhlmann** [Kruhlmann/gatekeeper#3]
Output template:

```typescript
`You (a ${playergender} ${player_race} ${player_role}
in <${guild_name}>) is attacking a level ${target_level}
${target_name} from the ${orientation} using your ${weapon_type}

Given these parameters what is the chance that your attacks are
parried (rounded up to nearest 1/10th)?`
```

**Comment by ResultsMayVary** [comment]
I spoke with magey and confirmed there is no known formula. 5% against a equal level mob and 14% against +3 are the only known values and could be used as a question. Weapon skill has no effect on chance.

**Comment by Kruhlmann** [comment]
Closing this as there is still no useful formula.
