### ISSUE TITLE
Bot should be extended to ask 3 question instead of only 1

### ISSUE THREAD

**Issue by Kruhlmann** [Kruhlmann/gatekeeper#37]
![image](https://user-images.githubusercontent.com/3380818/71526575-d7186000-28d7-11ea-8beb-700e5c581a3b.png)

**Comment by Kruhlmann** [comment]
These question should be from unique generators eg. not glancing three times in a row

**Comment by Kruhlmann** [comment]
This issue now has a working prototype in the i37 branch

**Comment by ResultsMayVary** [comment]
With #57 merged this should be resolved.
