### ISSUE TITLE
[CAPTCHA]

### ISSUE THREAD

**Issue by ohganot** [Kruhlmann/gatekeeper#78]
# CAPTCHA issue

CAPTHCA ID: `730d64b0-3c33-4705-8636-aec873b69d8d\ae79dc33-8741-4fc6-979f-178c7fbe3e74`

*Describe your problem in detail here. You can include screenshots and paste them directly into this text box.*

![image](https://user-images.githubusercontent.com/26059979/72205611-e1b52680-348d-11ea-819d-bd3ad1439f9f.png)

It should say if the question is about the yellow hit cap or white hit cap.

**Comment by Kruhlmann** [comment]
Closing this as it's a dupplicate of #69
