### ISSUE TITLE
%5BCAPTCHA%5D

### ISSUE THREAD

**Issue by thepopeofgrope** [Kruhlmann/gatekeeper#92]
# CAPTCHA issue

CAPTHCA ID: 6d6621df-14e8-4c86-ba16-68a1d0d543d8\a321865c-59ee-4b6b-bbf6-91f15619fdf

*Bot stopped responding after I answered the final captcha question after one prior wrong answer *
![582A1E0E-96A7-4C61-AF05-B443166EA7EC](https://user-images.githubusercontent.com/60016909/72643370-875c1000-393c-11ea-8947-df40bd1ad83a.png)

**Comment by Kruhlmann** [comment]
I had to do an emergency restart of the server. Please try answering the captcha again.
