### ISSUE TITLE
[CAPTCHA]

### ISSUE THREAD

**Issue by bipbob** [Kruhlmann/gatekeeper#93]
# CAPTCHA issue

CAPTHCA ID: `<f6a7ee94-c6a2-4016-b371-aa5e85296d06\6eb81bff-e464-46cb-872b-0db26cfa5ffa>`

Is the answer not 3.5? Is there a rule missing from the #formulas channel?
https://gyazo.com/0e2634d57cbde04bdd86411f4b463a2a
https://gyazo.com/0f58ec171a7263d397430d64ece485e8

Context for the rules in #formulas:
https://gyazo.com/8aca7479254885ad85d2c89f18dd62af
https://gyazo.com/3081d0d75984d6ca82dc003704cc6c58

**Comment by Kruhlmann** [comment]
I've verified the answer in the DB and it has correctly calculated the answer. Remember that you can at minimum get 1% hit.
