### ISSUE TITLE
insufficient information to answer captcha

### ISSUE THREAD

**Issue by wtfrank** [Kruhlmann/gatekeeper#96]
# CAPTCHA issue

"CAPTHCA ID: ffeae266-f38b-4033-88eb-f0fd73ff67af\e07b68b9-ac5e-4c99-95dc-4f0a7a4c1a80

You (a female gnome DPS fury warrior in <Unnatural Apes Wannabes>) are attacking a level 59 Firelord from behind using your dual wielded fists

Given these parameters what is the chance that your auto attacks land a glancing blow (rounded up to nearest 1/10th)?"

As we don't know what level I am, we don't know the chance of a glancing blow.

**Comment by Kruhlmann** [comment]
You're level 60.
