### ISSUE TITLE
[CAPTCHA]

### ISSUE THREAD

**Issue by fantom8** [Kruhlmann/gatekeeper#97]
# CAPTCHA issue

CAPTHCA ID: bb2bff9b-9271-462a-bb37-5ce7eebadbdf\9b5a9448-ae94-4e89-90f1-5e9c12b90631

"You (a non-binary gnome DPS fury warrior in <Lewd Scholars>) are attacking a level 58 Core Hound from the front using your dual wielded daggers

Given these parameters what is the chance that your attacks are dodged (rounded up to nearest 1/10th)?"

This question doesn't provide enough information to accurately answer the question. I don't know what my weapon skill is because it doesn't tell me 1) what my level is and 2) whether I am wearing any items that increase weapon skill.

I can of course assume that the intention is I am level 60 with no dagger skill increasing items, but for best results those things should be clarified.

**Comment by YourFavoritePerson** [comment]
also, why would i be attacking from the front here.  are you assuming my role or do you think i'm some sort of peasant.

**Comment by Kruhlmann** [comment]
Yes you're a level 60 gnome with 300 weapon skill.
