### ISSUE TITLE
[CAPTCHA]

### ISSUE THREAD

**Issue by AlexDudemeister** [Kruhlmann/gatekeeper#99]
# CAPTCHA issue

CAPTHCA ID: `<7448ab98-e9c4-4dff-bc6b-8142c2a922e6\62a6846c-1912-432c-a510-feb569ba5fd4>`

Gave an answer with a comma, which the bot accepted, which shouldn't be possible. At the second question, i answered with a comma, and the bot didn't accept it, which gave me some trouble.

![image](https://user-images.githubusercontent.com/60653805/73744365-ef8a5e80-4750-11ea-834b-653ef148550d.png)

**Comment by Kruhlmann** [comment]
Could you please include the incorrect answer as well? @AlexDudemeister

**Comment by AlexDudemeister** [comment]
![image](https://user-images.githubusercontent.com/60653805/73748734-5fe9ad80-475a-11ea-90f8-7390a4791547.png)

![image](https://user-images.githubusercontent.com/60653805/73748769-6ed06000-475a-11ea-8a4b-83081507b99f.png)

**Comment by Kruhlmann** [comment]
@ResultsMayVary what do you think of this?

**Comment by ResultsMayVary** [comment]
I propose two solutions.

1. Replace all commas with periods
2. Parse the input and only accept numbers, returning an error message to the user and not counting as a failure.

**Comment by Kruhlmann** [comment]
Fixed in f79eeb11f7b029730f9f50c91bb9781314037112
